rapidfort/community-images

- community_images/common/helpers.sh
- community_images/common/retry_helper.sh
- community_images/nats/bitnami/coverage.sh
- community_images/wordpress/bitnami/conftest.py
- community_images/wordpress/bitnami/functional_test.sh
- community_images/wordpress/bitnami/run.sh
- community_images/wordpress/bitnami/selenium_helper.sh
- community_images/wordpress/bitnami/wordpress_selenium_test.py
- scripts/setup.sh
this diff adds logging in the setup script to figure out the version of
docker-compose that we try to download in the github actions. There were
couple of intermittent issues in nats and wordpress image where the
coverage script pods start up failed because the pods were already
present since clean up didn't happen properly. The coverage script tries
to clean up the pods if present already before starting fresh ones.
Test Plan:
N/A
- fixes #
> add logging in the setup script and clean up pods

- scripts/setup.sh
Adds change for checking the docker compose version before installation so that docker compose installation is correct.
Test Plan:
Verified locally that if dc version comes out null, the default version is set
> Add a check on docker compose version in setup

- community_images/common/tests/mysql_coverage.sh
The mysqlbinlog command which is core functionality and does not cause any vulnerabilities was missing the coverage of the hardened images of bitnami/MySQL.
To resolve this error I needed to add the command in the mysql_coverage.sh, a file that was being used by other images including bitnami/MySQL, MySQL original, bitnami/MariaDB, and MariaDB original. Adding the command allows users to access the mysqlbinlog for all these images. 
This command allows users to read and analyze MySQL binary log files containing logs of database changes. 
This command allows users to read and analyze MySQL binary log files containing logs of database changes. 
This command can help in data recovery as well as debugging.
To successfully execute it for the bitnami version of the images, I needed to tag it …
> [Good to merge] mysqlbinlog command added to coverage

- .vscode/settings.json
- community_images/redis/bitnami/image.yml
- community_images/redis/ironbank/image.yml
- community_images/redis/official/dc_coverage.sh
- community_images/redis/official/docker.env.temp
- community_images/redis/official/image.yml
- Redis/official: added bookworm and alpine support since bullseye versions are 2 months old.
- Redis/bitnami: updated tags
- Redis/ironbank: updates search tag
> Updated tags for Redis 7 Support

- community_images/airflow/airflow/bitnami/image.yml
- community_images/apache/bitnami/image.yml
- community_images/couchdb/bitnami/image.yml
- community_images/elasticsearch/bitnami/image.yml
- community_images/envoy/bitnami/image.yml
- community_images/etcd/bitnami/image.yml
- community_images/fluent-bit/bitnami/image.yml
- community_images/fluentd/bitnami/image.yml
- community_images/ghost/bitnami/image.yml
- community_images/haproxy/bitnami/image.yml
- community_images/influxdb/bitnami/image.yml
- community_images/mariadb/bitnami/image.yml
- community_images/memcached/bitnami/image.yml
- community_images/mongodb/bitnami/image.yml
- community_images/mysql/bitnami/image.yml
- community_images/nats/bitnami/image.yml
- community_images/nginx/bitnami/image.yml
- community_images/node-exporter/bitnami/image.yml
- community_images/postgresql/bitnami/image.yml
- community_images/prometheus/bitnami/image.yml
- community_images/rabbitmq/bitnami/image.yml
- community_images/redis-cluster/bitnami/image.yml
- community_images/redis/bitnami/image.yml
- community_images/telegraf/bitnami/image.yml
- community_images/wordpress/bitnami/image.yml
- community_images/zookeeper/bitnami/image.yml
Updated base search tags for bitnami images:
- `airflow/airflow/bitnami`
- `apache/bitnami`
- `consul/bitnami`
- `couched/bitnami`
- `elastic search/bitnami`
- `envoy/bitnami`
- `etcd/bitnami`
- `fluent-bit/bitnami`
-  `fluentd/bitnami`
- `ghost/bitnami`
- `haproxy/bitnami`
- `influxes/bitnami`
- `mariadb/bitnami`
- `memcached/bitnami`
- `mongoldb/bitnami`
- `mysql/bitnami`
- `nats/bitnami`
- `nginx/bitnami`
- `node-exporter/bitnami`
- `postgresql/bitnami`
- `prometheus/bitnami`
- `rabbitmq/bitnami`
- `redis/bitnami`
- `redis-cluster/bitnami`
- `telegraf/bitnami`
- `wordpress/bitnami`
- `zookeeper/bitnami`
> Updated bitnami search tags in image.yml

- community_images/argocd/quay/image.yml
- community_images/argocd/quay/k8s_coverage.sh
Updated argocd dockerhub repo to `argocd` from `argocd-quay`.
Deletes CRDs in coverage scripts
> Argo CD updation

- .github/workflows/image_tags_check_v2.yml
- community_images/common/orchestrator/registry_helper.py
- scripts/image_tags_check_v2.py
- Created a script that gets base tags for all images in image.lst and for every base tag, it checks if we support the latest version. If we do not, it tells us the number of days we are lagging
- The script also sends all this data to data-receiver app which stores it in a SQL DB for analysis
- Also added a corresponding workflow yaml file for github actions
- QuayHelper in registry_helper was also having some pylint errors, so fixed those as well
> Image Tags Check WF v2

- community_images/common/orchestrator/coverage_runner.py
This PR adds config to run a script before raising pod/container/helm-chart.
1. Before/Setup scripts runs.
2. Runtime deployed
3. Coverage script runs
**Image.yml**
```yaml
...
runtimes:
- type: <type_of_runtime>
before_script: setup_script.sh
...
...
```
Sample setup_script.sh (use the name `docker_before.sh`, `dc_before.sh`, `k8s_before.sh` for convention)
```sh
set -x
set -e
JSON_PARAMS="$1"
JSON=$(cat "$JSON_PARAMS")
echo "Json params for docker compose coverage = $JSON"
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
```
> Added before script config

- community_images/kafka/ironbank/image.yml
- community_images/kafka/ironbank/overrides.yml
- Latest Coverage was failing because replicaCount: 3 was set in overrides.yml (which is not used in latest_coverage)
- 3 replicas are necessary for coverage script to run
Moved replicaCount to image.yml from overrides.yml
PS: Also improved the usage_instructions
> Kafka fix [Good to Merge]

- scripts/setup.sh
fixes the issue - urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker
ref: https://github.com/docker/docker-py/issues/3256
> adding requests to be specific to 2.31.0

- scripts/prepare_bitnami_tags.py
When newer images with subfolder named `bitnami-ironbank` were added, image_generator.sh script would fail.
This was because prepare_bitnami_tags.py script treated, say, postgres-exporter/bitnami-ironbank, as a bitnami image.
- Instead of substring search for "bitnami", added a strict equality comparison
- Tested by running the image_generator.sh script on VM
> Fix: Improved the regex in prepare_bitnami_tags.py for picking up only bitnami images

- community_images/vault/ironbank/image.yml
- ironbank_tags.yml
Fixing Vault-IB build failure due to an incorrect tag in the manifest. 
- Manually updated the correct tag in image.yml
- Commented out Vault-IB from ironbank_tags.yml
> Fix Vault-IB build failure

- community_images/vault/ironbank/image.yml
Fix vault-ib failing pipeline: https://github.com/rapidfort/community-images/actions/runs/10037302352/job/27736860238
1.14 repository is archived, updated the image.yml to use 1.15
> Fix vault-ib failing pipeline

- scripts/prepare_ironbank_tags.sh
There is an issue from ironbank side regarding the vault image. Ironbank has incorrectly marked the latest vault image version as “**9.1**” instead of “**1.7**”.
Our automated scripts pull information from ironbank and get the incorrect tag. Until the issue from ironbank is fixed, we are excluding this image for any automation script.
> Ignoring `vault/ironbank` until ironbank fix the wrong tag on their side

- community_images/thanos/ironbank/k8s_coverage.sh
Build for thanos-ib tends to fail randomly sometimes. While everything is technically fine, the error seems incidental. In an effort to make the coverage more robust, sleep of 30 seconds has been added before k8s_coverage to make sure that all the pods and services from both the charts are set up properly before coverage is executed.
> Added sleep in thanos-ib k8s_coverage to make it more robust

- community_images/vault/ironbank/image.yml
- scripts/prepare_ironbank_tags.sh
- Changed the tag to 1.15
- 1.17 is having problems getting pulled from registry. Possibly because of wrong tag in hardening manifest.
> Use 1.15 as Vault-IB tag 

- community_images/mongodb/bitnami/overrides.yml
Fixed the RF_RW_DIR env var issue by setting readOnlyRootFilesystem to false in overrides.yml for k8s runtime
> Set readOnlyRootFilesystem to false in overrides.yml for k8s runtime for mongodb

- community_images/apache/bitnami/overrides.yml
Fixed the RF_RW_DIR env var issue by setting readOnlyRootFilesystem to false in overrides.yml for k8s runtime
> Set readOnlyRootFilesystem to false in overrides of k8s runtime

- .github/workflows/zulip_notification_bot.yml
Update Zulip Bot with the following features: 
- Track last two runs of `Image Creation Run` workflow
- Report images failing consecutively in the last two runs.
- Send alerts on Zulip separately for Ironbank and Non-Ironbank images.
> Update Zulip Bot to manage image creation run alerts

- community_images/common/templates/image_readme.j2
- report_shots/shots.js
- added generating merged vunls svg
> Readme updater Merged two vulnerability charts into one svg

- community_images/concourse/official/image.yml
- community_images/couchdb/official/image.yml
- community_images/elasticsearch/ironbank/image.yml
- community_images/keycloak/ironbank/image.yml
- community_images/mariadb/official/image.yml
This PR syncs the latest changes from RapidFort CI Team
> Sync Latest Images and Updates by Team RapidFort

- community_images/common/templates/image_yml_params.yml
- community_images/common/templates/main_readme.j2
> Common - Updated common folder
