README.md, community_images/mariadb/bitnami/README.md, community_images/mongodb/bitnami/README.md, community_images/mysql/bitnami/README.md, community_images/postgresql/bitnami/README.md, community_images/redis-cluster/bitnami/README.md, community_images/redis/bitnami/README.md
=> Fix badges in image

community_images/common/tests/redis_coverage.sh, community_images/redis/bitnami/functional_test.sh, community_images/redis/bitnami/run.sh
=> Add redis benchmark

community_images/redis-cluster/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/run.sh
=> Add redis-benchmark for redis-cluster

community_images/mysql/bitnami/functional_test.sh
=> add mysql benchmark

community_images/postgresql/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/docker-compose.yml.base, community_images/redis-cluster/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/run.sh, community_images/redis/bitnami/functional_test.sh, community_images/redis/bitnami/run.sh
=> Add docker ft

community_images/postgresql/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/functional_test.sh, community_images/redis/bitnami/docker-compose.yml.base, community_images/redis/bitnami/functional_test.sh, community_images/redis/bitnami/run.sh
=> add redis docker compose

community_images/mysql/bitnami/docker-compose.yml.base, community_images/mysql/bitnami/functional_test.sh, community_images/mysql/bitnami/run.sh, community_images/postgresql/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/functional_test.sh, community_images/redis/bitnami/functional_test.sh
=> Add mysql dc

community_images/common/tests/sysbench_tests.sh, community_images/mariadb/bitnami/docker-compose.yml.base, community_images/mariadb/bitnami/functional_test.sh, community_images/mariadb/bitnami/run.sh, community_images/mysql/bitnami/functional_test.sh
=> Add mariadb docker and docker compose

community_images/mongodb/bitnami/functional_test.sh, community_images/mongodb/bitnami/perf_test/Dockerfile, community_images/mongodb/bitnami/perf_test/entrypoint.sh
=> Add mongodb perf test

community_images/mongodb/bitnami/docker-compose.yml.base, community_images/mongodb/bitnami/functional_test.sh, community_images/mongodb/bitnami/run.sh
=> Add mongodb docker and docker-compose scripts

community_images/mariadb/bitnami/overrides.yml, community_images/mongodb/bitnami/overrides.yml, community_images/mysql/bitnami/overrides.yml, community_images/postgresql/bitnami/overrides.yml, community_images/redis-cluster/bitnami/overrides.yml, community_images/redis/bitnami/overrides.yml
=> Add rf_verbose env variable

community_images/common/tests/mongodb_coverage.sh, community_images/common/tests/mysql_coverage.sh, community_images/mariadb/bitnami/run.sh, community_images/mongodb/bitnami/run.sh, community_images/mysql/bitnami/run.sh
=> Add utils for mongo and mysql, mariadb

.github/workflows/image_publisher.yml, community_images/common/dockertags, community_images/common/helpers.sh
=> Compare tag

.github/workflows/reviewdog.yml, community_images/common/delete_tag.sh, community_images/common/helpers.sh, community_images/common/tests/sysbench_tests.sh, community_images/mariadb/bitnami/functional_test.sh, community_images/mariadb/bitnami/run.sh, community_images/mongodb/bitnami/functional_test.sh, community_images/mongodb/bitnami/perf_test/build_docker.sh, community_images/mongodb/bitnami/run.sh, community_images/mysql/bitnami/functional_test.sh, community_images/mysql/bitnami/run.sh, community_images/postgresql/bitnami/functional_test.sh, community_images/postgresql/bitnami/run.sh, community_images/redis-cluster/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/redis_cluster_runner.sh, community_images/redis-cluster/bitnami/run.sh, community_images/redis/bitnami/functional_test.sh, community_images/redis/bitnami/run.sh, scripts/cleanup_readme_dh.sh, scripts/image_publisher.sh, scripts/prb_executor.sh, scripts/setup.sh, scripts/update_readme_dh.sh
Signed-off-by: Vinod Gupta <vinod@rapidfort.com>
- fixes #
=> add shell check

.github/workflows/readme_updater.yml, community_images/common/templates/image_readme.j2, community_images/mariadb/bitnami/README.md, community_images/mariadb/bitnami/readme.yml, community_images/mongodb/bitnami/README.md, community_images/mongodb/bitnami/readme.yml, community_images/mysql/bitnami/README.md, community_images/mysql/bitnami/readme.yml, community_images/postgresql/bitnami/README.md, community_images/postgresql/bitnami/readme.yml, community_images/redis-cluster/bitnami/README.md, community_images/redis-cluster/bitnami/readme.yml, community_images/redis/bitnami/README.md, community_images/redis/bitnami/readme.yml, scripts/image_readme_generator.sh
=> Update image rm

community_images/common/dockertags, community_images/mariadb/bitnami/run.sh
=> Add all tags

community_images/mongodb/bitnami/run.sh, community_images/mysql/bitnami/run.sh, community_images/postgresql/bitnami/run.sh, community_images/redis-cluster/bitnami/run.sh, community_images/redis/bitnami/run.sh
=> add additional tags for remaining images

community_images/mariadb/bitnami/overrides.yml, community_images/mongodb/bitnami/overrides.yml, community_images/mysql/bitnami/overrides.yml, community_images/postgresql/bitnami/overrides.yml, community_images/redis-cluster/bitnami/docker-compose.yml.base, community_images/redis-cluster/bitnami/overrides.yml, community_images/redis/bitnami/overrides.yml
=> Reduce rc nodes

community_images/mariadb/bitnami/overrides.yml, community_images/mongodb/bitnami/overrides.yml, community_images/mysql/bitnami/overrides.yml, community_images/postgresql/bitnami/overrides.yml, community_images/redis-cluster/bitnami/overrides.yml
=> reduce size

community_images/common/helpers.sh, community_images/mariadb/bitnami/overrides.yml, community_images/mariadb/bitnami/run.sh, community_images/mongodb/bitnami/overrides.yml, community_images/mongodb/bitnami/run.sh, community_images/mysql/bitnami/overrides.yml, community_images/mysql/bitnami/run.sh, community_images/postgresql/bitnami/overrides.yml, community_images/postgresql/bitnami/run.sh, community_images/redis-cluster/bitnami/overrides.yml, community_images/redis-cluster/bitnami/run.sh, community_images/redis/bitnami/overrides.yml, community_images/redis/bitnami/run.sh
=> Create multiple tags, fix limits and PR creation

community_images/common/helpers.sh, community_images/mariadb/bitnami/functional_test.sh, community_images/mariadb/bitnami/run.sh, community_images/mongodb/bitnami/functional_test.sh, community_images/mongodb/bitnami/run.sh, community_images/mysql/bitnami/functional_test.sh, community_images/mysql/bitnami/run.sh, community_images/nginx/bitnami/functional_test.sh, community_images/nginx/bitnami/run.sh, community_images/postgresql/bitnami/functional_test.sh, community_images/postgresql/bitnami/run.sh, community_images/redis-cluster/bitnami/functional_test.sh, community_images/redis-cluster/bitnami/run.sh, community_images/redis/bitnami/functional_test.sh, community_images/redis/bitnami/run.sh
=> Add exponential backoff

community_images/envoy/bitnami/README.md, community_images/envoy/bitnami/configs/envoy.yaml, community_images/envoy/bitnami/image.yml, community_images/envoy/bitnami/run.sh
=> force tls1.3

community_images/common/helpers.sh, scripts/setup.sh
=> Fix image pull count reporting shell scripts

.github/workflows/envoy_bitnami.yml, .github/workflows/mariadb_bitnami.yml, .github/workflows/mongodb_bitnami.yml, .github/workflows/monitor.yml, .github/workflows/mysql_bitnami.yml, .github/workflows/nginx_bitnami.yml, .github/workflows/postgresql_bitnami.yml, .github/workflows/redis-cluster_bitnami.yml, .github/workflows/redis_bitnami.yml, community_images/common/helpers.sh, community_images/common/templates/image_run.yml.j2, community_images/common/templates/monitor.yml.j2
=> add counters using curl

community_images/envoy/bitnami/functional_test.sh, community_images/envoy/bitnami/run.sh, community_images/nginx/bitnami/run.sh
=> add tls backoff

community_images/envoy/bitnami/docker-compose.yml.base, community_images/nginx/bitnami/docker-compose.yml.base
=> Use only ipv4 for envoy, nginx

community_images/nginx/bitnami/README.md, community_images/nginx/bitnami/image.yml, community_images/nginx/bitnami/run.sh
=> add nginx 123

.github/workflows/envoy_bitnami.yml, .github/workflows/fluentd_bitnami.yml, .github/workflows/mariadb_bitnami.yml, .github/workflows/mongodb_bitnami.yml, .github/workflows/mysql_bitnami.yml, .github/workflows/nginx_bitnami.yml, .github/workflows/oncall_grafana.yml, .github/workflows/postgresql_bitnami.yml, .github/workflows/redis-cluster_bitnami.yml, .github/workflows/redis_bitnami.yml, community_images/common/templates/image_run.yml.j2, community_images/nginx/bitnami/README.md, community_images/nginx/bitnami/image.yml
=> fix readme

community_images/redis-cluster/bitnami/README.md, community_images/redis-cluster/bitnami/image.yml, community_images/redis-cluster/bitnami/run.sh, community_images/redis/bitnami/README.md, community_images/redis/bitnami/image.yml, community_images/redis/bitnami/run.sh
=> upgrade redis to redis 7.0.3

community_images/common/Dockerfile.base, community_images/common/helpers.sh, community_images/common/libbitnami.sh, community_images/nginx/bitnami/functional_test.sh, community_images/nginx/bitnami/run.sh
=> Add rf message

community_images/oncall/grafana/.env_hobby, community_images/oncall/grafana/docker-compose.yml.base, community_images/oncall/grafana/functional_test.sh, community_images/oncall/grafana/run.sh
=> Fix grafana

.github/workflows/nats_bitnami_v2.yml, community_images/common/orchestrator/main.py
=> Add nats v2 yaml to github actions and fix PR checks

.github/workflows/httpd_bitnami.yml, .github/workflows/monitor.yml, .github/workflows/readme_updater.yml, README.md, community_images/httpd/bitnami/README.md, community_images/httpd/bitnami/image.yml, frontrow.csv, image.lst
Please check httpd's image.yml and README.md
Let me know if anything's missing.
=> Httpd with image.yml and readme.md

community_images/apache/bitnami/functional_test.sh
- Fixed apache benchmark testing for Apache Image.
=> ab test fixed for apache

.github/workflows/apache_bitnami.yml, .github/workflows/envoy_bitnami.yml, .github/workflows/etcd_bitnami.yml, .github/workflows/fluentd_bitnami.yml, .github/workflows/influxdb_bitnami.yml, .github/workflows/mariadb_bitnami.yml, .github/workflows/mongodb_bitnami.yml, .github/workflows/mysql_bitnami.yml, .github/workflows/nats_bitnami.yml, .github/workflows/nginx_bitnami.yml, .github/workflows/nginx_ironbank.yml, .github/workflows/oncall_grafana.yml, .github/workflows/postgresql_bitnami.yml, .github/workflows/postgresql_ironbank.yml, .github/workflows/prometheus_bitnami.yml, .github/workflows/rabbitmq_bitnami.yml, .github/workflows/redis-cluster_bitnami.yml, .github/workflows/redis_bitnami.yml, .github/workflows/redis_ironbank.yml, .github/workflows/wordpress_bitnami.yml, community_images/common/templates/image_run.yml.j2, community_images/common/templates/image_run_v2.yml.j2, community_images/redis-cluster/bitnami/k8s_coverage.sh
=> Give more memory to mini kube

community_images/common/orchestrator/coverage_runner.py, community_images/common/orchestrator/harden_generator.py, community_images/common/orchestrator/main.py, community_images/common/orchestrator/stub_generator.py, community_images/common/orchestrator/tag_manager.py, community_images/nginx/bitnami/README.md, community_images/nginx/bitnami/image.yml, community_images/nginx/bitnami/run.sh
=> Split repo sets and tag mappings

community_images/redis/bitnami/k8s_coverage.sh
=> Fix redis 823

community_images/mongodb/bitnami/image.yml
update the docker hub account name for mongodb community image
=> update docker hub account name

community_images/airflow/bitnami/k8s_coverage.sh, community_images/airflow/bitnami/selenium_tests/test_testadmin.py, community_images/airflow/bitnami/selenium_tests/test_viewbrowse.py, community_images/prometheus/bitnami/coverage.sh, community_images/wordpress/bitnami/k8s_coverage.sh
=> Fix selenium logs

community_images/common/orchestrator/coverage_runner.py
=> fix common commands relative path

README.md, community_images/airflow/airflow-scheduler/bitnami/README.md, community_images/airflow/airflow-worker/bitnami/README.md, community_images/airflow/airflow/bitnami/README.md, community_images/apache/bitnami/README.md, community_images/common/templates/image_readme.j2, community_images/common/templates/main_readme.j2, community_images/envoy/bitnami/README.md, community_images/etcd/bitnami/README.md, community_images/fluentd/bitnami/README.md, community_images/influxdb/bitnami/README.md, community_images/mariadb/bitnami/README.md, community_images/mongodb/bitnami/README.md, community_images/mysql/bitnami/README.md, community_images/nats/bitnami/README.md, community_images/nginx/bitnami/README.md, community_images/nginx/ironbank/README.md, community_images/oncall/grafana/README.md, community_images/postgresql/bitnami/README.md, community_images/postgresql/ironbank/README.md, community_images/prometheus/bitnami/README.md, community_images/rabbitmq/bitnami/README.md, community_images/redis-cluster/bitnami/README.md, community_images/redis/bitnami/README.md, community_images/redis/ironbank/README.md, community_images/wordpress/bitnami/README.md
=> Update utm codes 09 22

README.md, community_images/airflow/airflow-scheduler/bitnami/README.md, community_images/airflow/airflow-worker/bitnami/README.md, community_images/airflow/airflow/bitnami/README.md, community_images/apache/bitnami/README.md, community_images/common/templates/image_readme.j2, community_images/common/templates/main_readme.j2, community_images/envoy/bitnami/README.md, community_images/etcd/bitnami/README.md, community_images/fluentd/bitnami/README.md, community_images/influxdb/bitnami/README.md, community_images/mariadb/bitnami/README.md, community_images/mongodb/bitnami/README.md, community_images/mysql/bitnami/README.md, community_images/nats/bitnami/README.md, community_images/nginx/bitnami/README.md, community_images/nginx/ironbank/README.md, community_images/oncall/grafana/README.md, community_images/postgresql/bitnami/README.md, community_images/postgresql/ironbank/README.md, community_images/prometheus/bitnami/README.md, community_images/rabbitmq/bitnami/README.md, community_images/redis-cluster/bitnami/README.md, community_images/redis/bitnami/README.md, community_images/redis/ironbank/README.md, community_images/wordpress/bitnami/README.md
=> Add utm rf links

community_images/curl/curlimages/docker_coverage.sh
=> Improve curl

community_images/common/orchestrator/harden_generator.py, community_images/common/tests/common_commands.sh, community_images/common/tests/postgres_coverage.sh, community_images/common/tests/test.my_sql, community_images/common/tests/test.psql, community_images/postgresql/bitnami/docker-compose.yml
=> Add pg tzdata

community_images/common/orchestrator/registry_helper.py, scripts/setup.sh
=> Fix retry issues

.pylintrc, community_images/common/orchestrator/k8s_setup.py, community_images/common/orchestrator/utils.py, community_images/common/templates/image_yml_params.yml
Add health check script support for k8s resource type in image.yml
Tested with a dummy health check script for zookeeper image
=> Add health check script k8s

scripts/delete_rf_stub.py
=> Cleanup old rfstubs

community_images/common/orchestrator/coverage_runner.py, community_images/common/orchestrator/main.py, community_images/common/orchestrator/registry_helper.py
=> Find version tag, fix traefik

community_images/common/orchestrator/docker_compose_setup.py, community_images/common/orchestrator/registry_helper.py
=> fix missing digest

community_images/common/orchestrator/docker_compose_setup.py
Fix docker-compose logs in __exit__ method
=> Fix docker compose cmd to use env-file

community_images/fluentd/bitnami/docker-compose.yml, scripts/tests_required.py
Signed-off-by: Vinod Gupta <vinod@rapidfort.com>
- fixes #
=> run fluentd in non-root mode

community_images/common/orchestrator/tag_manager.py
Fixes the image generation logic for multi container image. we should set the image generation to true for all containers if any of the image needs a regeneration.
=> Fix the needs generation logic for container images

community_images/postgresql/bitnami/.rfignore, community_images/postgresql/bitnami/docker-compose.yml, community_images/postgresql/bitnami/image.yml
- Added support for POSTGRESQL_SHARED_PRELOAD_LIBRARIES
=> Postgres fix by anmol (Ref: [Bug]: #236)

community_images/common/orchestrator/harden_generator.py, community_images/common/orchestrator/registry_helper.py, community_images/common/orchestrator/tag_manager.py, community_images/haproxy/bitnami/configs/sample-server/app/app.py, community_images/haproxy/official/configs/sample-server/app/app.py
Reverts rapidfort/community-images#260
=> Revert "Fix image tagging"

community_images/common/orchestrator/harden_generator.py, community_images/common/orchestrator/registry_helper.py, community_images/common/orchestrator/tag_manager.py, community_images/haproxy/bitnami/configs/sample-server/app/app.py, community_images/haproxy/official/configs/sample-server/app/app.py
Reverts rapidfort/community-images#263
=> Revert "Revert "Fix image tagging""

community_images/ghost/bitnami/selenium_tests/test_settingUp.py
=> Ghost Fix - Anmol

community_images/common/tests/mysql_coverage.sh
- Added mysqld_safe to mysql_coverage.sh
=> [Good to merge] Added mysqld_safe functionality for bitnami/mysql and bitnami/mariadb

community_images/apache/bitnami/.rfignore, community_images/apache/bitnami/coverage_script.sh, community_images/apache/official/.rfignore
Created a new file .rfignore and a change in the coverage_script.sh file to add the missing functionality of the environment variables.
header files will be added and it will cover the changes in coverage_script
- fixes # 
- [Bug]: Missing of the core functionality (http_protocol.h http_request.h http_main.h) files.
=> [Good to Merge] added .rfignore file and change in coverage_script

community_images/postgresql/official/image.yml
=> PostgreSQL Official Fix: Anmol

community_images/yugabyte/yugabytedb/docker_coverage.sh
- Added fix for yugabyte/yugabytedb.
=> YUGABYTE-FIX : Anmol

community_images/common/tests/mysql_coverage.sh
Updated mysql coverage script to include missing binaries(i.e. `mysqlpump` and `mysql_ssl_rsa_setup`) present in original mysql images and absent in original mariadb images.
- fixes #249 
- fixes #252
=> [Good to merge] Update to mysql_coverage.sh script

community_images/yugabyte/yugabytedb/dc_coverage.sh, community_images/yugabyte/yugabytedb/image.yml
=> altered wait time

community_images/yugabyte/yugabytedb/image.yml
=> Added 2.18. support for yugabyte

community_images/common/orchestrator/docker_compose_setup.py, community_images/postgresql/bitnami/dc_coverage.sh, community_images/postgresql/bitnami/docker_coverage.sh
=> Remove volumes after docker-compose down

community_images/postgresql/ironbank/.rfignore, community_images/postgresql/ironbank/docker-compose.yml
added timezone env and zoneinfo directory to .rfignore
=> Fixing runtime timezone 

community_images/nginx/ironbank/dc_coverage.sh
=> Fixed nginx ironbank

community_images/haproxy/bitnami/configs/haproxy-tcp.cfg, community_images/haproxy/bitnami/overrides.yml
Will fix the haproxy run failure.
- fixes #
=> Haproxy Fixing [Do not merge]

community_images/mysql/ironbank/image.yml
Fixed Mysql ironbank
- fixes #
=> Fixed Mysql ironbank

community_images/common/orchestrator/coverage_runner.py, community_images/common/orchestrator/k8s_setup.py, community_images/common/orchestrator/main.py
* If `--namespace` flag is **not specified** then namespace will be created and deleted in end.
* If `--namespace` flag is **specified** and namespace is **not present** then namespace will be created and deleted in end.
* If `--namespace` flag is **specified** and namespace is **present** then namespace will neither be created nor deleted in end but any **Release/Pod/Deployment will be created and deleted** at end.
=> Added config to read --namespace flag

scripts/setup.sh
=> Trying to fix CLI

community_images/nats/bitnami/coverage.sh, community_images/nats/ironbank/coverage.sh, community_images/nats/official/coverage.sh
Updated go modules file path in coverage script
=> [Bug Fix] : changed the go  module's file path in coverage.sh

community_images/nats/official/image.yml
Nats -official fix (tag updation)
=> Tag Updation for nats-official

community_images/mysql/bitnami/README.md, community_images/mysql/bitnami/image.yml, community_images/redis/bitnami/README.md, community_images/redis/bitnami/image.yml, image-api.lst
Rolling back locking of redis/bitnami and mysql/bitnami
=> Rollback for locking of mysql and redis bitnami images

community_images/zookeeper/bitnami/coverage.sh, community_images/zookeeper/bitnami/k8s_coverage.sh
Changed coverage_script dir form opt to tmp
=> Zookeeper coverage fix

community_images/common/orchestrator/commands.py, community_images/common/orchestrator/coverage_runner.py, community_images/common/orchestrator/main.py
`python3 ../common/orchestrator/main.py stub_coverage nginx/official --image-to-scan=nginx:1.25.4-bookworm-rf-rfstub`
=> Added support for quick test coverage

community_images/kong/official/image.yml
=> kong helm version change

community_images/common/selenium_tests/python-chromedriver/Dockerfile, community_images/common/selenium_tests/python-chromedriver/build_docker.sh
Old Image : https://hub.docker.com/r/joyzoursky/python-chromedriver
New Image : https://hub.docker.com/r/schukinpavel/python-chromedriver
=> Updated Python-chromedriver version

community_images/common/orchestrator/coverage_runner.py, community_images/common/orchestrator/tag_manager.py, scripts/image_tags_check.py, scripts/image_tags_check_v2.py
=> pylint error removal

community_images/nginx/official/configs/nginx.conf.load_modules, community_images/nginx/official/dc_before.sh, community_images/nginx/official/image.yml
- nginx slim does not container modules.
=> Added slim support for nginx

community_images/ansible/ironbank/dc_coverage.sh, community_images/ansible/ironbank/docker-compose.yml
=> Ansible coverage fix

community_images/rabbitmq/official/commands.sh, community_images/rabbitmq/official/dc_coverage.sh, community_images/rabbitmq/official/docker-compose.yml
- adding rabbitmq cli coverage
=> update in rabbitmq-official coverage

community_images/fluentd/ironbank/dc_coverage.sh, community_images/fluentd/official/dc_coverage.sh
- Fluentd-official and Fluentd-ironbank update
=> updating fluentd coverage

community_images/fluent-bit/official/docker-compose.yml
=> change in image as dependency

community_images/kibana/ironbank/docker-compose.yml, community_images/kibana/ironbank/selenium_tests/kibana_selenium_test.py
- changes due to tag update in Kibana
=> update in kibana

community_images/fluent-bit/official/dc_coverage.sh
=> fluent-bit official pid removal

community_images/wordpress/ironbank/dc_coverage.sh
=> wordpress-ib test

community_images/nats/ironbank/coverage.sh, community_images/nats/ironbank/image.yml
Changed K8s Runtime from no_helm to helm
=> Nats Iron Bank Fix

community_images/vcluster/ironbank/k8s_before.sh
Fix vCluster Iron Bank Build failures
- fixes #
=> Fix vCluster Iron Bank Build failures

community_images/mysql/ironbank/docker_coverage.sh, community_images/mysql/ironbank/image.yml
Fix MySQL-IB Build Failures occurring due to deprecated authentication plugin.
=> Fix MySQL-IB Build Failures

community_images/grafana/ironbank/docker-compose.yml, community_images/grafana/ironbank/selenium_tests/grafana_selenium_test.py
=> grafana coverage updation

community_images/fluxcd-helm-controller/ironbank/harden_overrides.yml, community_images/fluxcd-helm-controller/ironbank/image.yml, community_images/fluxcd-image-automation-controller/ironbank/harden_overrides.yml, community_images/fluxcd-image-automation-controller/ironbank/image.yml, community_images/fluxcd-image-automation-controller/ironbank/k8s_coverage.sh, community_images/fluxcd-image-reflector-controller/ironbank/harden_overrides.yml, community_images/fluxcd-image-reflector-controller/ironbank/image.yml, community_images/fluxcd-image-reflector-controller/ironbank/k8s_coverage.sh, community_images/fluxcd-kustomize-controller/ironbank/harden_overrides.yml, community_images/fluxcd-kustomize-controller/ironbank/image.yml, community_images/fluxcd-kustomize-controller/ironbank/k8s_coverage.sh, community_images/fluxcd-notification-controller/ironbank/harden_overrides.yml, community_images/fluxcd-notification-controller/ironbank/image.yml, community_images/fluxcd-notification-controller/ironbank/k8s_coverage.sh, community_images/fluxcd-source-controller/ironbank/harden_overrides.yml, community_images/fluxcd-source-controller/ironbank/image.yml, community_images/fluxcd-source-controller/ironbank/k8s_coverage.sh
- added overrides for harden images of fluxed controllers
- add pod logs
=> fluxcd controller fix

community_images/gatekeeper/ironbank/harden_overrides.yml, community_images/gatekeeper/ironbank/image.yml
=> Gatekeeper IronBank Fix

community_images/logstash/ironbank/dc_coverage.sh, community_images/logstash/ironbank/docker-compose.yml
=> adding dynamic ports in logstash

community_images/metabase/ironbank/docker-compose.yml, community_images/metabase/ironbank/selenium_tests/metabase_selenium_test.py, community_images/terragrunt/ironbank/dc_coverage.sh
- command update for terragrunt
- dependency change for met abase
=> changing terragrunt and metabase

community_images/prometheus-config-reloader/ironbank/image.yml, community_images/prometheus-config-reloader/ironbank/overrides.yml, community_images/prometheus-config-reloader/ironbank/prometheus-health-check.sh
prometheus-config-reloader build fix
- fixes #
=> prometheus-config-reloader Build Fix

.github/workflows/dependency-review.yml, .github/workflows/mongodb_perf_build.yml, .github/workflows/prometheus_flaskapp_build.yml, .github/workflows/python_chrome_driver.yml, .github/workflows/reviewdog.yml
=> workflow changes

scripts/remove_rfstub_tags.py
Addition of remove-rfstub-tags script
- fixes #
=> Addition of remove-rfstub-tags script

community_images/airflow/airflow-scheduler/bitnami-ironbank/image.yml, community_images/airflow/airflow-worker/bitnami-ironbank/image.yml, community_images/airflow/airflow/bitnami/image.yml, community_images/ansible/ironbank/image.yml, community_images/cass/ironbank/image.yml, community_images/dex/ironbank/image.yml, community_images/eck-operator/ironbank/image.yml, community_images/elasticsearch/bitnami/image.yml, community_images/fluent-bit/bitnami/image.yml, community_images/fluentd/bitnami/image.yml, community_images/gatekeeper/ironbank/image.yml, community_images/ghost/bitnami/image.yml, community_images/gitaly/ironbank/image.yml, community_images/gitlab-kas/ironbank/image.yml, community_images/grafana-plugins/ironbank/image.yml, community_images/influxdb/bitnami/image.yml, community_images/keycloak/official/themes/keycloak/common/resources/node_modules/text-security/assets/circle.svg, community_images/keycloak/official/themes/keycloak/common/resources/node_modules/text-security/assets/disc.svg, community_images/keycloak/official/themes/keycloak/common/resources/node_modules/text-security/assets/square.svg, community_images/kyverno-background-controller/ironbank/image.yml, community_images/kyverno-cleanup-controller/ironbank/image.yml, community_images/kyverno-reports-controller/ironbank/image.yml, community_images/mariadb/bitnami/image.yml, community_images/nginx/bitnami/image.yml, community_images/postfix/ironbank/image.yml, community_images/prometheus-config-reloader/ironbank/image.yml, community_images/prometheus-operator/ironbank/image.yml, community_images/telegraf/bitnami/image.yml, community_images/vcluster/ironbank/image.yml, image.lst
This PR syncs the latest changes from AnmolVirdi
=> Sync Latest Images and Updates by AnmolVirdi

.github/workflows/image_run_pr_v3.yml, .github/workflows/image_run_v3.yml, .github/workflows/monitor.yml, .github/workflows/readme_updater.yml, builder.lst, image.lst
=> adding image-creation workflows

scripts/ib_pipelines_check.py
- Update ib_pipelines_checker python script to search the logs and report images that have completed partial coverage. 
- Fix Pylint Issues.
=> Update IB Pipelines Checker workflow

community_images/gitlab-kas/ironbank/image.yml, community_images/mariadb/bitnami/image.yml, community_images/rabbitmq/bitnami/image.yml, image.lst
This PR syncs the latest changes from Pranav Sinha, merged by AnmolVirdi
=> Sync Latest Images and Updates by Pranav Sinha

scripts/ib_pipelines_check.py
=> Fix Pylint Errors

community_images/boundary/ironbank/image.yml, community_images/consul/bitnami/image.yml, community_images/couchdb/bitnami/image.yml, community_images/elasticsearch/bitnami/image.yml, community_images/ghost/bitnami/image.yml, community_images/mariadb/bitnami/image.yml, community_images/memcached/bitnami/image.yml, community_images/moodle/ironbank/image.yml, community_images/mysql/bitnami/image.yml, community_images/nats/bitnami/image.yml, community_images/redis-exporter/ironbank/image.yml, community_images/shellcheck/official/image.yml, community_images/yq/official/image.yml
This PR syncs the latest changes from Uday Beswal, merged by AnmolVirdi
=> Sync Latest Images and Updates by Uday Beswal

community_images/common/templates/image_readme.j2, report_shots/shots.js
- fixed some test hardcode
- fixed charts path
=> - fixed path, removed some hardcode

community_images/common/templates/image_readme.j2
- fixed charts max-width
- changed appearence of vulns
=> - readme charts polishing

report_shots/shots.js
- removed 0 entries from vulns count line chart
=> - small fix for vulns count view

community_images/nginx/official/image.yml, community_images/pgbouncer/official/image.yml, community_images/postgresql/bitnami-ironbank/image.yml, community_images/tomcat-openjdk8/ironbank/image.yml
This PR syncs the latest changes from RapidFort CI Team
=> Sync Latest Images and Updates by Team RapidFort

.github/workflows/image_run_pr_v3.yml, .github/workflows/image_run_v3.yml, community_images/common/templates/image_run_v3.yml.j2
- changing ubuntu version from latest to 22.04
=> changing ubuntu version

.github/workflows/zulip_notification_bot.yml, scripts/ib_pipelines_check.py
Increase Timeouts for API calls in github workflows and scripts to track and report IB Pipelines
=> Increase Timeout in IB Pipeline Tracker Workflow

.github/workflows/mysql_dbt2_benchmark.yml
Workflow build added for MySQL DBT2 Benchmark tests. This will build the image required for benchmarking the mysql database.
=> workflow to build mysql dbt2 benchamrk image created

.github/workflows/image_run_v3.yml, community_images/common/templates/image_run_v3.yml.j2
=> Workflow fix

.github/workflows/image_run_v3.yml
=> Workflow - Updated RF_ROOT_URL envs to run
